swagger: "2.0"
info:
  title: albums-api
  description: Albums API Sample
  version: 1.0.0

host: albums-api.apigateway.myfinance-409219.cloud.goog
# basePath: /v1
schemes:
  - https


paths:  
  /albums:
    get:
      summary: Retrieve list of albums
      operationId: listAlbums
      x-google-backend:
        address: https://apiserver-axdcnvcnfa-ew.a.run.app/albums
      produces: 
        - application/json
      responses:
        200:
          description:  "Successfully get a list of albums"
          schema:
            type: string
  